In [1]:
import pandas as pd

In [2]:
results = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]}, index=["one","two"])

In [3]:
results.to_csv("results.csv")

In [4]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [3]:
housing_data = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [60]:
housing_data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [7]:
housing_data.shape

(3000, 9)

In [8]:
housing_data.longitude
#or
housing_data["longitude"]

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [9]:
            #columns ,rows
housing_data.longitude[:5]
#or
housing_data["longitude"][:5]

0   -122.05
1   -118.30
2   -117.81
3   -118.36
4   -119.67
Name: longitude, dtype: float64

In [10]:
                #rows,columns
housing_data.iloc[:5,:5]#index based
housing_data.iloc[[1,3,4],[1,3,5]]

   latitude  total_rooms  population
1     34.26       1510.0       809.0
3     33.82         67.0        49.0
4     36.33       1241.0       850.0

In [22]:
                #rows,columns
housing_data.loc[:5,"latitude"]#label based. also noticed about the slicing range
housing_data.loc[[1,3,4],["latitude", "population"]]

   latitude  population
1     34.26       809.0
3     33.82        49.0
4     36.33       850.0

In [24]:
housing_data.set_index("longitude")

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...
-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [25]:
housing_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [26]:
series1 = housing_data.total_rooms >=3000

In [27]:
series1

0        True
1       False
2        True
3       False
4       False
        ...
2995    False
2996     True
2997    False
2998    False
2999    False
Name: total_rooms, Length: 3000, dtype: bool

In [28]:
housing_data.loc[series1]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
17,-121.20,38.69,26.0,3077.0,607.0,1603.0,595.0,2.7174,137500.0
...,...,...,...,...,...,...,...,...,...
2981,-120.66,35.49,17.0,4422.0,945.0,2307.0,885.0,2.8285,171300.0
2984,-117.59,33.88,13.0,3239.0,849.0,2751.0,813.0,2.6111,107000.0
2987,-121.97,37.29,25.0,4096.0,743.0,2027.0,741.0,5.3294,300300.0
2991,-117.17,34.28,13.0,4867.0,718.0,780.0,250.0,7.1997,253800.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0

In [30]:
series1 = ((housing_data.total_rooms >=3000) & (housing_data.median_income > 6)) | (housing_data.housing_median_age < 4)

In [31]:
series1

0        True
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Length: 3000, dtype: bool

In [32]:
housing_data.loc[series1]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
19,-122.59,38.01,35.0,8814.0,1307.0,3450.0,1258.0,6.1724,414300.0
78,-118.75,34.17,18.0,6217.0,858.0,2703.0,834.0,6.8075,325900.0
79,-122.47,37.99,22.0,7274.0,1002.0,2468.0,957.0,7.4940,439200.0
102,-121.31,38.62,31.0,3114.0,430.0,1121.0,456.0,6.2440,240000.0
...,...,...,...,...,...,...,...,...,...
2917,-122.59,38.04,25.0,3412.0,455.0,1238.0,406.0,8.3646,397300.0
2925,-122.00,37.12,17.0,4413.0,672.0,1674.0,608.0,6.9772,383300.0
2936,-119.75,36.87,3.0,13802.0,2244.0,5226.0,1972.0,5.0941,143700.0
2963,-118.07,33.80,34.0,3486.0,507.0,1311.0,503.0,7.1221,384500.0
2991,-117.17,34.28,13.0,4867.0,718.0,780.0,250.0,7.1997,253800.0

In [ ]:
# reviews.loc[reviews.country.isin(['Italy', 'France'])]

In [41]:
housing_data.isnull()
housing_data.notnull()
series1 = housing_data.total_rooms.notnull()
housing_data.total_rooms[series1]
housing_data[series1].total_rooms

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [43]:
housing_data["myIndex"] = range(len(housing_data), 0, -1)

In [44]:
housing_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,myIndex
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1

In [45]:
housing_data.rename(columns={'median_house_value': 'median_valuation'})

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_valuation,myIndex
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1

In [46]:
housing_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,myIndex
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1

In [47]:
housing_data.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,myIndex
firstEntry,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000
secondEntry,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1

In [48]:
housing_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,myIndex
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1

In [49]:
housing_data.rename_axis("houses", axis='rows').rename_axis("fields", axis='columns')

fields,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,myIndex
houses,,,,,,,,,,
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1

In [ ]:
# # when joining datasets that have same columns. so end of the all rows of the first then the second datasets rows start.
# canadian_youtube = pd.read_csv("../input/youtube-new/CAvideos.csv")
# british_youtube = pd.read_csv("../input/youtube-new/GBvideos.csv")

# pd.concat([canadian_youtube, british_youtube])

In [ ]:
# #when they have common index.don't have the all same columns but the conjunction of comns are not null. so make the conjuction index then make it join by index
# left = canadian_youtube.set_index(['title', 'trending_date'])
# right = british_youtube.set_index(['title', 'trending_date'])

# left.join(right, lsuffix='_CAN', rsuffix='_UK')

In [58]:
housing_data.describe()
housing_data.population.describe()
housing_data.population.mean()
# housing_data.population.unique()
# housing_data.population.value_counts()

1402.7986666666666

In [57]:
deviation_population = housing_data.population.mean()
housing_data["deviation_population"] = housing_data.population.map(lambda p: p - deviation_population)#returns a series
housing_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,myIndex,deviation_population
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,3000,134.201333
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,2999,-593.798667
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,2998,81.201333
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,2997,-1353.798667
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,2996,-552.798667
...,...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,5,-144.798667
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,4,2093.201333
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,3,-709.798667
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,2,-1356.798667
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,1,-649.798667

In [6]:
deviation_population = housing_data.population.mean()
def remean_points(row):
    row.population = row.population - deviation_population
    return row

housing_data.apply(remean_points, axis='columns')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,134.201333,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,-593.798667,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,81.201333,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,-1353.798667,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,-552.798667,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,-144.798667,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,2093.201333,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,-709.798667,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,-1356.798667,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,-649.798667,260.0,8.5608,500001.0

In [9]:
housing_data.iloc[housing_data.housing_median_age.idxmax()]

longitude               -122.420000
latitude                  37.760000
housing_median_age        52.000000
total_rooms             3587.000000
total_bedrooms          1030.000000
population               856.201333
households               979.000000
median_income              2.540300
median_house_value    250000.000000
Name: 26, dtype: float64

In [10]:
bedsPerRoom = housing_data.total_bedrooms/housing_data.total_rooms
bedsPerRoom

0       0.170142
1       0.205298
2       0.141265
3       0.223881
4       0.196616
          ...
2995    0.442759
2996    0.205821
2997    0.210251
2998    0.145833
2999    0.149008
Length: 3000, dtype: float64

In [2]:
passengers = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/test.csv")

In [13]:
passengers.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [11]:
passengers.groupby("Sex").Sex.size()
passengers.groupby("Sex").Sex.count()

Sex
female    152
male      266
Name: Sex, dtype: int64

In [14]:
def edAg(age):
  if age<30:
    return "Learning"
  elif age<60:
    return "Working"
  return "Retired"

passengers["Education"] = passengers.Age.map(edAg)
passengers.groupby("Fare")

In [15]:
passengers

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Education
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Working
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Working
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Retired
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Learning
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Learning
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Retired
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,Working
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Working
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Retired
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,Retired

In [18]:
passengers.groupby("Fare").Age.min()
passengers.groupby("Fare").Pclass.min()

Fare
0.0000      1
3.1708      3
6.4375      3
6.4958      3
6.9500      3
           ..
227.5250    1
247.5208    1
262.3750    1
263.0000    1
512.3292    1
Name: Pclass, Length: 169, dtype: int64

In [19]:
passengers.groupby("Education").Age.max()

Education
Learning    29.0
Retired     76.0
Working     59.0
Name: Age, dtype: float64

In [23]:
passengers.groupby("Fare").apply(lambda row: row.Age.max())

Fare
0.0000      49.0
3.1708       9.0
6.4375       NaN
6.4958      21.0
6.9500      30.0
            ...
227.5250    47.0
247.5208    27.0
262.3750    61.0
263.0000    60.0
512.3292    58.0
Length: 169, dtype: float64

In [44]:
temp = passengers.groupby(["Education","Embarked"]).apply(lambda row: row.loc[passengers.Sex=='male', ["PassengerId",	"Pclass"	,"Name",	"Sex",	"Age"	,"SibSp"	,"Parch"	,"Ticket"	,"Fare",	"Cabin"]])
tempindex = temp.index
print(type(tempindex))
temp = temp.reset_index()
temp
passengers.groupby("Embarked").apply(lambda x:x.loc[passengers.Age > 0])

<class 'pandas.core.indexes.multi.MultiIndex'>

,Education,Embarked,level_2,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,Learning,C,17,909,3,"Assaf, Mr. Gerios",male,21.0,0,0,2692,7.2250,NaN
1,Learning,C,23,915,1,"Williams, Mr. Richard Norris II",male,21.0,0,1,PC 17597,61.3792,NaN
2,Learning,C,27,919,3,"Daher, Mr. Shedid",male,22.5,0,0,2698,7.2250,NaN
3,Learning,C,35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.5,0,0,2682,7.2292,NaN
4,Learning,C,51,943,2,"Pulbaum, Mr. Franz",male,27.0,0,0,SC/PARIS 2168,15.0333,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Working,S,378,1270,1,"Hipkins, Mr. William Edward",male,55.0,0,0,680,50.0000,C39
262,Working,S,387,1279,2,"Ashby, Mr. John",male,57.0,0,0,244346,13.0000,NaN
263,Working,S,393,1285,2,"Gilbert, Mr. William",male,47.0,0,0,C.A. 30769,10.5000,NaN
264,Working,S,401,1293,2,"Gale, Mr. Harry",male,38.0,1,0,28664,21.0000,NaN
265,Working,S,415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN

In [32]:
passengers.groupby("Education").Fare.agg([len, min, max])

           len     min       max
Education
Learning   185  3.1708  263.0000
Retired    100  0.0000  263.0000
Working    133  0.0000  512.3292

In [49]:
passengers.sort_values(by='Age', ascending=False)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Education
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,Retired
81,973,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S,Retired
236,1128,1,"Warren, Mr. Frank Manley",male,64.0,1,0,110813,75.2500,D37,C,Retired
305,1197,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S,Retired
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C,Retired
...,...,...,...,...,...,...,...,...,...,...,...,...
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q,Retired
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q,Retired
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Retired
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Retired
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,Retired

In [66]:
passengers.loc[passengers.Age<30].sort_index()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Education
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Learning
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Learning
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S,Learning
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S,Learning
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C,Learning
...,...,...,...,...,...,...,...,...,...,...,...,...
403,1295,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S,Learning
405,1297,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C,Learning
406,1298,2,"Ware, Mr. William Jeffery",male,23.0,1,0,28666,10.5000,NaN,S,Learning
409,1301,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,Learning
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S,Learning

In [68]:
passengers.loc[passengers.Age<30].sort_index()
passengers.sort_values(by=["Embarked", "Age"])

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Education
296,1188,2,"Laroche, Miss. Louise",female,1.0,1,2,SC/Paris 2123,41.5792,NaN,C,Learning
80,972,3,"Boulos, Master. Akar",male,6.0,1,1,2678,15.2458,NaN,C,Learning
196,1088,1,"Spedden, Master. Robert Douglas",male,6.0,0,2,16966,134.5000,E34,C,Learning
161,1053,3,"Touma, Master. Georges Youssef",male,7.0,1,1,2650,15.2458,NaN,C,Learning
283,1175,3,"Touma, Miss. Maria Youssef",female,9.0,1,1,2650,15.2458,NaN,C,Learning
...,...,...,...,...,...,...,...,...,...,...,...,...
365,1257,3,"Sage, Mrs. John (Annie Bullen)",female,NaN,1,9,CA. 2343,69.5500,NaN,S,Retired
382,1274,3,"Risien, Mrs. Samuel (Emma)",female,NaN,0,0,364498,14.5000,NaN,S,Retired
384,1276,2,"Wheeler, Mr. Edwin Frederick""""",male,NaN,0,0,SC/PARIS 2159,12.8750,NaN,S,Retired
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Retired
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Retired

In [74]:
passengers.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Education       object
dtype: object

In [73]:
passengers.Age.dtypes

dtype('float64')

In [72]:
passengers.Parch.astype("int64")

0      0
1      0
2      0
3      0
4      1
      ..
413    0
414    0
415    0
416    0
417    1
Name: Parch, Length: 418, dtype: int64

In [76]:
pd.isnull(passengers.Age)
passengers.loc[pd.isnull(passengers.Age)]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Education
10,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S,Retired
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S,Retired
29,921,3,"Samaan, Mr. Elias",male,NaN,2,0,2662,21.6792,NaN,C,Retired
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Retired
36,928,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S,Retired
...,...,...,...,...,...,...,...,...,...,...,...,...
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q,Retired
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q,Retired
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Retired
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Retired
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,Retired

In [81]:
passengers.Age = passengers.Age.fillna("unknown")

In [82]:
passengers.iloc[10]

PassengerId                 902
Pclass                        3
Name           Ilieff, Mr. Ylio
Sex                        male
Age                     unknown
SibSp                         0
Parch                         0
Ticket                   349220
Fare                     7.8958
Cabin                       NaN
Embarked                      S
Education               Retired
Name: 10, dtype: object

In [88]:
passengers.Age = passengers.Age.replace("unknown","DNK")

In [89]:
passengers.Age.unique()

array([34.5, 47.0, 62.0, 27.0, 22.0, 14.0, 30.0, 26.0, 18.0, 21.0, 'DNK',
       46.0, 23.0, 63.0, 24.0, 35.0, 45.0, 55.0, 9.0, 48.0, 50.0, 22.5,
       41.0, 33.0, 18.5, 25.0, 39.0, 60.0, 36.0, 20.0, 28.0, 10.0, 17.0,
       32.0, 13.0, 31.0, 29.0, 28.5, 32.5, 6.0, 67.0, 49.0, 2.0, 76.0,
       43.0, 16.0, 1.0, 12.0, 42.0, 53.0, 26.5, 40.0, 61.0, 60.5, 7.0,
       15.0, 54.0, 64.0, 37.0, 34.0, 11.5, 8.0, 0.33, 38.0, 57.0, 40.5,
       0.92, 19.0, 36.5, 0.75, 0.83, 58.0, 0.17, 59.0, 14.5, 44.0, 5.0,
       51.0, 3.0, 38.5], dtype=object)